project:
  type: website
  output-dir: docs

website:
  site-url: https://economicsofbiodiversity.org/
  twitter-card:
    card-style: summary
    title: "URKI Economics of Biodiversity"
    image: "images/EB_logo_favicon_greenleaf.png"
    description: "Website for the NERC/ESRC Economics of Biodiversity programme."
    creator: "@buchanding"
  search: false
  title: "Economics of Biodiversity"
  favicon: images/EB_logo_favicon_greenleaf.png
  navbar:
    pinned: true
    logo: images/EB_logo_favicon_greenleaf.png
    right:
      - href: index.qmd#about
        text: About
      - href: projects.qmd
        text: Funded projects
      - news_posts.qmd
      - contact.qmd
  page-footer:
    border: true
    left: |
     ![](/images/nerc_logos/UKRI_NER_Council-Logo_Horiz-RGB.png){width=220px}
     ![](/images/nerc_logos/UKRI_ESR_Council-Logo_Horiz-RGB.png){width=220px}
    right: |
     [econ.biodiv@uea.ac.uk](mailto:econ.biodiv@uea.ac.uk)
     ![](/images/EB_logo_footer.png){height=70px}

format:
  html:
    resources:
      - "audio/SP1114_Farmland_arable_2019.mp3"
    anchor-sections: false
    theme: styles_simplex.scss
    toc: false
    page-layout: custom
    smooth-scroll: true
    link-external-newwindow: true
